version: '3'
services:
  mysql:
    image: library/mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: >
      --server-id=1
      
  redis:
      image: redis/redis-stack
      container_name: redis
      ports:
        - 6379:6379
        - 8001:8001 # redis insight
      environment:
        REDIS_ARGS: "--requirepass systempass"

# docker compose -p msa_exam up -d