spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0